### ISSUE TITLE
can you upload configs/training_dataset/p3_eight_qa.json?

### ISSUE THREAD

**Issue by daidaiershidi** [r-three/mats#2]
@dptam Great work! I'm a beginner in this field, could you explain what "p3_eight_qa" refers to? Also, could you upload the p3_eight_qa.json file from the configs/training_dataset directory, please?

**Comment by dptam** [comment]
Thanks for pointing it out. That config was actually renamed to `p3_multitask.json` - I just fixed the README. 
`p3_eight_qa` refers to training a multitask model on the eight dataset mixture in the paper. The instruction format comes from P3.  The training mixture is actually specified here: `https://github.com/r-three/mats/blob/cb52c388d5e0c2035c76fe4a326c444b8198a5a7/configs/training_run/p3_eight_qa_T0_run.json#L2`

**Comment by daidaiershidi** [comment]
Thank you very much for your answers and help.

**Comment by daidaiershidi** [comment]
https://github.com/r-three/mats/blob/cb52c388d5e0c2035c76fe4a326c444b8198a5a7/src/eval/Scorer.py#L1

Hello, may I ask if this 'load' is from the evaluate.py file (src/eval/evaluate.py), or is evaluate a separate Python library? Additionally, is the code for K-FAC approximation the same as diagonalFisher? How Z and O' in Eq. (11) are obtained?

**Comment by dptam** [comment]
The `load` is from the [huggingface](https://github.com/huggingface/evaluate) evaluate library.  

Z and O' are computed in https://github.com/r-three/mats/blob/main/src/merging/save_metadata/save_gram_matrix.py where Z is the input activations and O' is the output activation gradient. 

The merging is done in https://github.com/r-three/mats/blob/main/src/merging/conjugateGradient_fisherMerging.py where by default, only Z is used, and `--use_backward` has to be to set to True to use O'

We only included Z and not O' in the uploaded checkpoints on Google Cloud since O' is not used in our final model, so O' would have to be recomputed.

**Comment by daidaiershidi** [comment]
Thank you for your explanation. I tried the gradient and found that ```grad_output[0].float() ≈ 1e-7```. Have you encountered this phenomenon in your experiments?

**Comment by dptam** [comment]
Yes, I also saw something similar where the gradient of the output activations was that small (or even smaller but I don't remember the exact number).

**Comment by daidaiershidi** [comment]
https://github.com/r-three/mats/blob/cb52c388d5e0c2035c76fe4a326c444b8198a5a7/src/merging/conjugateGradient_fisherMerging.py#L359
final_model is the output of cg_forwar/cg_forwardBackward，and you say  `# Add the non-merged weights` in previous line. So I guess it is `final_model[parameter_name] += parameter`?

**Comment by dptam** [comment]
The non-merged weights do not exist in the final model, so adding them to the final model means just setting the parameter_name to the parameter. 
The non-merged weights come because K-FAC only merges linear layers, so for non-linear layers (called non-merged weights), we just use simple averaging.

**Comment by daidaiershidi** [comment]
I completely understand, thank you very much for bringing such great work.
